name: CI Tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  basic_checks:
    name: Basic environment and code checks / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          miniconda-version: "latest"
          use-mamba: "true"
      - name: Python info
        run: |
          which python
          python --version
      - name: Show conda info and list
        run: |
          conda info
          conda list
      - name: Show pip list
        run: |
          pip list
      - name: Linting (with black)
        run: |
          black --line-length 120 --check --diff .
      - name: Run tests
        run: |
          pytest
